// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeJkf3LOPaVUCTBj_tJAGt1MHoqmmwG3M',
    appId: '1:632807416449:web:a1a9ba67b05277d6cf6380',
    messagingSenderId: '632807416449',
    projectId: 'first-app-9f38a',
    authDomain: 'first-app-9f38a.firebaseapp.com',
    storageBucket: 'first-app-9f38a.firebasestorage.app',
    measurementId: 'G-4Q723KBGZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrWm1tGsdQSSN0RYiLf6B8-v_FyzNhThs',
    appId: '1:632807416449:android:2c689802cfa65aabcf6380',
    messagingSenderId: '632807416449',
    projectId: 'first-app-9f38a',
    storageBucket: 'first-app-9f38a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpMvxvxXDlNXJHQRIZCwf16-vHlwt2f0g',
    appId: '1:632807416449:ios:794b20a8c3583d02cf6380',
    messagingSenderId: '632807416449',
    projectId: 'first-app-9f38a',
    storageBucket: 'first-app-9f38a.firebasestorage.app',
    iosBundleId: 'com.example.daftarKaryawan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpMvxvxXDlNXJHQRIZCwf16-vHlwt2f0g',
    appId: '1:632807416449:ios:794b20a8c3583d02cf6380',
    messagingSenderId: '632807416449',
    projectId: 'first-app-9f38a',
    storageBucket: 'first-app-9f38a.firebasestorage.app',
    iosBundleId: 'com.example.daftarKaryawan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeJkf3LOPaVUCTBj_tJAGt1MHoqmmwG3M',
    appId: '1:632807416449:web:02c43e2b2f0c1296cf6380',
    messagingSenderId: '632807416449',
    projectId: 'first-app-9f38a',
    authDomain: 'first-app-9f38a.firebaseapp.com',
    storageBucket: 'first-app-9f38a.firebasestorage.app',
    measurementId: 'G-N7J289PTDD',
  );
}
